-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:31:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Фильмы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Фильмы` (
  `id_фильма` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(150) NOT NULL,
  `режиссер` VARCHAR(100) NULL,
  `длительность_мин` INT NULL,
  `возрастной_рейтинг` VARCHAR(10) NULL,
  PRIMARY KEY (`id_фильма`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Залы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Залы` (
  `id_зала` INT NOT NULL AUTO_INCREMENT,
  `номер` INT NOT NULL,
  `вместимость` INT NOT NULL,
  `тип` VARCHAR(20) NULL,
  PRIMARY KEY (`id_зала`),
  UNIQUE INDEX `номер_UNIQUE` (`номер` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Кресла`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Кресла` (
  `id_кресла` INT NOT NULL AUTO_INCREMENT,
  `ряд` INT NOT NULL,
  `место` INT NOT NULL,
  `id_зала` INT NULL,
  PRIMARY KEY (`id_кресла`),
  INDEX `id_зала_idx` (`id_зала` ASC) VISIBLE,
  CONSTRAINT `id_зала`
    FOREIGN KEY (`id_зала`)
    REFERENCES `mydb`.`Залы` (`id_зала`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сеансы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сеансы` (
  `id_сеанса` INT NOT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `время` TIME NOT NULL,
  `цена` DECIMAL(10,2) NULL,
  `id_фильма` INT NULL,
  `id_зала2` INT NULL,
  PRIMARY KEY (`id_сеанса`),
  INDEX `id_фильма_idx` (`id_фильма` ASC) VISIBLE,
  INDEX `id_зала_idx` (`id_зала2` ASC) VISIBLE,
  CONSTRAINT `id_фильма`
    FOREIGN KEY (`id_фильма`)
    REFERENCES `mydb`.`Фильмы` (`id_фильма`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_зала2`
    FOREIGN KEY (`id_зала2`)
    REFERENCES `mydb`.`Залы` (`id_зала`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Покупатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупатели` (
  `id_покупателя` INT NOT NULL AUTO_INCREMENT,
  `имя` VARCHAR(100) NULL,
  `телефон` VARCHAR(20) NULL,
  PRIMARY KEY (`id_покупателя`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Билеты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Билеты` (
  `id_билета` INT NOT NULL AUTO_INCREMENT,
  `статус` VARCHAR(45) NULL,
  `id_сеанса` INT NULL,
  `id_кресла` INT NULL,
  `id_покупателя` INT NULL,
  PRIMARY KEY (`id_билета`),
  INDEX `id_сеанса_idx` (`id_сеанса` ASC) VISIBLE,
  INDEX `id_кресла_idx` (`id_кресла` ASC) VISIBLE,
  INDEX `id_покупателя_idx` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `id_сеанса`
    FOREIGN KEY (`id_сеанса`)
    REFERENCES `mydb`.`Сеансы` (`id_сеанса`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_кресла`
    FOREIGN KEY (`id_кресла`)
    REFERENCES `mydb`.`Кресла` (`id_кресла`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_покупателя`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_покупателя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
